all:    udp

unix:
	logger --priority=local2.debug XXX

tcp:
	logger --priority=local2.debug --tcp --port 514 --server 127.0.0.1 XXX


udp:
	logger --priority=local2.debug --udp --port 514 --server 127.0.0.1 XXX
